### ISSUE TITLE
Android 11进入直播间崩溃

### ISSUE THREAD

**Issue by Snowy-syp** [polyv/polyv-android-cloudClass-sdk-demo#10]
报错信息;
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference

**Comment by HWilliamgo** [comment]
参考[快速集成](https://github.com/polyv/polyv-android-cloudClass-sdk-demo/wiki/2-%E5%BF%AB%E9%80%9F%E9%9B%86%E6%88%90)的环境要求的第三点，有对android 11的兼容配置做说明。
