### ISSUE TITLE
直播详情

### ISSUE THREAD

**Issue by FOnlyJack** [polyv/polyv-android-cloudClass-sdk-demo#2]
如何获取老师介绍的详情和直播介绍的详情呢?

**Comment by FOnlyJack** [comment]
@jlayi   再看下这个问题呗    这只能自己调接口查询吧,sdk里有实体吗?

**Comment by jlayi** [comment]
目前没有，您那边可以先调接口查询，如果要需要的话可以提需求给我们产品哈。另外问题多的话可以和我们技术支持对接，那样效率比较高。

**Comment by FOnlyJack** [comment]
@jlayi  嗯嗯   知道了  麻烦了
