### ISSUE TITLE
怎么适配AndroidX

### ISSUE THREAD

**Issue by jabbarwockeez** [polyv/polyv-android-cloudClass-sdk-demo#5]
rt

**Comment by kedouyun** [comment]
怎么适配AndroidX

**Comment by SHLURENJIA** [comment]
可根据[云课堂Androidx适配指南](https://github.com/polyv/polyv-android-cloudClass-sdk-demo/wiki/%E4%BA%91%E8%AF%BE%E5%A0%82Androidx%E9%80%82%E9%85%8D%E6%8C%87%E5%8D%97)操作
