### ISSUE TITLE
集成进项目爆红alipaySdk冲突

### ISSUE THREAD

**Issue by hanqingkai** [polyv/polyv-android-cloudClass-sdk-demo#6]
Duplicate class com.ta.utdid2.a.a.a found in modules alicloud-android-utdid-1.1.5.4.jar (com.aliyun.ams:alicloud-android-utdid:1.1.5.4) and classes.jar (:alipaySdk-15.6.5-20190718211148:)

阿里云都用的什么版本或者把所有的引入包在文档中体现一下，方便解决冲突，客服一直无人回复

**Comment by Panway** [comment]
用Gradle构建一直出现下面这种错误

```
Failed to resolve: com.aliyun.ams:alicloud-android-utdid:1.1.5.4
Show in Project Structure dialog
```

找到 commonui/build.gradle文件，增加一个`exclude module:'alicloud-android-utdid'`就好了，我是新手😂

灵感来自：https://github.com/wonday/react-native-aliyun-push/issues/113 ，全局搜`api (`解决的

```
api ('com.easefun.polyv:polyvSDKCloudClass:0.14.0.11'){
    exclude module:'alicloud-android-utdid'
    exclude group:'com.github.bumptech.glide',module:'glide'
}
```
