### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by xwdz** [polyv/polyv-android-cloudClass-sdk-demo#8]
既然是SDK那么请保持Api对外的一直性，尽量考虑从内部解决问题，而不是经常更改暴露的接口。
作为接入方每次更新都需要花额外的时间进行整理，检查。
希望贵公司能认真考虑该问题

**Comment by Yukino0812** [comment]
感谢您的反馈，团队内部会对此进行反思，在接下来的版本中控制接口的变更。
